[package]
name = "feignhttp"
version = "0.0.1"
authors = ["code-mcx <1827939333@qq.com>"]
edition = "2018"
description = "Use rust macros to decorate http call"
readme = "README.md"


[workspace]
members = ["codegen"]


[dependencies]
feignhttp-codegen = { path = "codegen" }

http = "0.2"

serde = { version = "1" }
reqwest = { version = "0.11", features = ["json"] }


[dev-dependencies]
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
