[package]
name = "feignhttp"
version = "0.0.1"
authors = ["dxx <1827939333@qq.com>"]
edition = "2018"
description = "Declarative HTTP client for rust"
documentation = ""
homepage = "https://github.com/code-mcx/feignhttp"
repository = "https://github.com/code-mcx/feignhttp"
categories = ["web-programming::http-client"]
keywords = ["http", "request", "client"]
readme = "README.md"
license = "MIT"

exclude = [
    "examples/**",
]


[workspace]
members = ["codegen"]


[dependencies]
feignhttp-codegen = { version = "0.0.1", path = "codegen" }

http = "0.2"
serde = "1"
reqwest = { version = "0.11", features = ["json"] }


[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
